<footer>
  <section class="footerlinks">
    <a href="https://www.swinburne.edu.au" target="_blank"><strong>Call us on</strong> (03) 8234 6777</a>
    <a href="mailto:PhantomPixel@gmail.com">PhantomPixel@gmail.com</a>
    <a href="https://github.com/105964253/Phantom-Pixelpart02" target="_blank">GitHub</a>
    <a href="https://techops-webproject.atlassian.net/jira/software/projects/SCRUM/summary" target="_blank">Jira</a>
  </section>

  <section class="footerbottom">
    <p>&copy; 2025 Phantom Pixel. All rights reserved.</p>
  </section>
</footer>

