<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Recruiting Tech employees for a game development studio">
  <meta name="keywords" content="Tech, Game Development, Careers">
  <meta name="author" content="Phantom Pixel">
  <title>Phantom Pixel</title>

  <link rel="stylesheet" href="styles/styles.css">
  <link rel="stylesheet" href="styles/fonts.css">
</head>

<!-- Content including slogans and all the statistics are generated using gen ai. -->
<body id="indexbody"> <!-- Gave it a unique id so that styling would not overlap. -->

<header id="header01">
  <div id="logo">
    <a href="index.php">
      <img src="styles/Images/phantompixellogo.png" id="phantompixellogo" alt="phantom pixel logo" width="200" />
    </a>
  </div>
