<nav id="header01nav">
    <a href="index.php" style="font-family: Pixelade; font-size: 18px;">HOME</a>
    <a href="about.php" style="font-family: Pixelade; font-size: 18px;">ABOUT</a>
    <a href="jobs.php" style="font-family: Pixelade; font-size: 18px;">CAREERS</a>
    <a href="apply.php" style="font-family: Pixelade; font-size: 18px;">APPLY NOW</a>
    <a href="login.php" style="font-family: Pixelade; font-size: 18px;">LOGIN</a>
  </nav>

</header>
